import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { getAuthToken } from "../lib/auth";
import { Colors, Typography } from "../theme/typography";

const API=process.env.EXPO_PUBLIC_TWITOK_API_URL??"http://localhost:4000/api/v1";
type Studio={profile?:any;monetization?:any[];recentContent?:any[];analytics?:any[]};

export default function CreatorStudioScreen(){
 const [data,setData]=useState<Studio|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const t=await getAuthToken();if(!t)throw new Error("Sign in required");const r=await fetch(API+"/creator/studio/me",{headers:{Authorization:"Bearer "+t}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Creator Studio unavailable");setData(d);}catch(e){setError(e instanceof Error?e.message:"Creator Studio unavailable");}finally{setLoading(false);}})();},[]);
 if(loading)return <View style={styles.center}><ActivityIndicator color={Colors.text}/><Text style={styles.muted}>Loading Creator Studio…</Text></View>;
 if(error)return <View style={styles.center}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>router.back()}><Text style={styles.link}>Go back</Text></Pressable></View>;
 const analytics=Array.isArray(data?.analytics)?data!.analytics:[]; const content=Array.isArray(data?.recentContent)?data!.recentContent:[]; const money=Array.isArray(data?.monetization)?data!.monetization:[];
 const total=(key:string)=>analytics.reduce((n:any,x:any)=>n+Number(x?.[key]??0),0);
 return <View style={styles.root}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Creator Studio</Text><View style={{width:30}}/></View><ScrollView contentContainerStyle={styles.content}>
 <Text style={styles.heading}>{data?.profile?.displayName||"Creator dashboard"}</Text><Text style={styles.sub}>Analytics, content management and monetization.</Text>
 <View style={styles.grid}>{[["Views",total("views")],["Likes",total("likes")],["Comments",total("comments")],["Shares",total("shares")]].map(([k,v])=><View key={String(k)} style={styles.card}><Text style={styles.cardValue}>{Number(v).toLocaleString()}</Text><Text style={styles.cardLabel}>{k}</Text></View>)}</View>
 <Text style={styles.section}>Monetization</Text><View style={styles.panel}><Text style={styles.panelTitle}>{money.length?"Programs available":"Creator monetization"}</Text><Text style={styles.panelText}>{money.length?money.map((m:any)=>String(m.program||"Program")).join(" • "):"Monetization programs will appear here when you become eligible."}</Text></View>
 <Text style={styles.section}>Recent content</Text>{content.length?content.map((item:any,i:number)=><View key={String(item._id||item.id||i)} style={styles.contentRow}><View style={styles.dot}><Text style={styles.dotText}>▶</Text></View><View style={{flex:1}}><Text style={styles.rowTitle} numberOfLines={1}>{item.title||item.caption||"Published content"}</Text><Text style={styles.rowSub}>{item.status||"CONTENT"} · {Number(item.views??0).toLocaleString()} views</Text></View></View>):<View style={styles.panel}><Text style={styles.panelText}>Your published content and performance will appear here.</Text></View>}
 </ScrollView></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},center:{flex:1,backgroundColor:Colors.background,alignItems:"center",justifyContent:"center",padding:24,gap:10},header:{height:58,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:Colors.border},back:{color:Colors.text,fontSize:34},title:{color:Colors.text,...Typography.section},content:{padding:18,paddingBottom:40},heading:{color:Colors.text,...Typography.title},sub:{color:Colors.textSecondary,...Typography.body,marginTop:5},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:18},card:{width:"48%",backgroundColor:Colors.surface,borderRadius:12,borderWidth:1,borderColor:Colors.border,padding:15},cardValue:{color:Colors.text,...Typography.numeric},cardLabel:{color:Colors.textSecondary,...Typography.caption,marginTop:3},section:{color:Colors.text,...Typography.section,marginTop:24,marginBottom:10},panel:{backgroundColor:Colors.surface,borderRadius:12,borderWidth:1,borderColor:Colors.border,padding:16},panelTitle:{color:Colors.text,...Typography.bodySemibold},panelText:{color:Colors.textSecondary,...Typography.body,marginTop:5},contentRow:{flexDirection:"row",alignItems:"center",paddingVertical:12,borderBottomWidth:1,borderBottomColor:Colors.border},dot:{width:42,height:42,borderRadius:8,backgroundColor:Colors.surfaceRaised,alignItems:"center",justifyContent:"center",marginRight:12},dotText:{color:Colors.text},rowTitle:{color:Colors.text,...Typography.bodyMedium},rowSub:{color:Colors.textSecondary,...Typography.caption,marginTop:2},muted:{color:Colors.textSecondary,...Typography.caption},error:{color:Colors.danger,...Typography.body,textAlign:"center"},link:{color:Colors.text,...Typography.label}});
