import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { getAuthToken } from "../lib/auth";
import { Colors, Typography } from "../theme/typography";

const API=process.env.EXPO_PUBLIC_TWITOK_API_URL??"http://localhost:4000/api/v1";
type Conversation={id:string;otherUser?:{username?:string;nickname?:string}|null;lastMessagePreview?:string|null;updatedAt?:string};
type Message={_id:string;senderId:string;text:string;createdAt:string;status?:string};

export default function MessagesScreen(){
 const [items,setItems]=useState<Conversation[]>([]);const [active,setActive]=useState<Conversation|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState("");const [username,setUsername]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function request(path:string,init:RequestInit={}){
  const token=await getAuthToken();if(!token)throw new Error("Sign in required");
  const r=await fetch(API+path,{...init,headers:{Authorization:"Bearer "+token,"Content-Type":"application/json",...(init.headers||{})}});
  const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Request failed");return d;
 }
 async function load(){try{setItems((await request("/messages/conversations")).conversations??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load messages");}}
 async function open(c:Conversation){setActive(c);try{setMessages((await request("/messages/conversations/"+c.id+"/messages")).messages??[]);await request("/messages/conversations/"+c.id+"/delivered",{method:"POST"});await request("/messages/conversations/"+c.id+"/read",{method:"POST"});}catch(e){setError(e instanceof Error?e.message:"Unable to load conversation");}}
 async function start(){if(!username.trim())return;setBusy(true);try{const d=await request("/messages/conversations/direct",{method:"POST",body:JSON.stringify({username:username.trim()})});setUsername("");const c={id:d.conversation._id,otherUser:null};await load();await open(c);}catch(e){setError(e instanceof Error?e.message:"Unable to start conversation");}finally{setBusy(false);}}
 async function send(){if(!active||!text.trim())return;setBusy(true);try{await request("/messages/conversations/"+active.id+"/messages",{method:"POST",body:JSON.stringify({text:text.trim()})});setText("");await open(active);}catch(e){setError(e instanceof Error?e.message:"Unable to send message");}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 if(active)return <View style={styles.root}><View style={styles.header}><Pressable onPress={()=>setActive(null)}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>@{active.otherUser?.username||"Conversation"}</Text><View style={{width:30}}/></View><FlatList data={messages} keyExtractor={m=>m._id} contentContainerStyle={styles.chat} renderItem={({item})=><View style={styles.message}><Text style={styles.messageText}>{item.text}</Text><Text style={styles.time}>{new Date(item.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</Text></View>} ListEmptyComponent={<Text style={styles.empty}>No messages yet.</Text>}/><View style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Type a message..." placeholderTextColor={Colors.textMuted} style={styles.input}/><Pressable onPress={send} disabled={busy||!text.trim()} style={[styles.send,(!text.trim()||busy)&&styles.disabled]}><Text style={styles.sendText}>➤</Text></Pressable></View></View>;
 return <View style={styles.root}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Messages</Text><View style={{width:30}}/></View><View style={styles.start}><TextInput value={username} onChangeText={setUsername} placeholder="Start chat with @username" placeholderTextColor={Colors.textMuted} autoCapitalize="none" style={styles.input}/><Pressable onPress={start} disabled={busy||!username.trim()} style={[styles.newButton,(!username.trim()||busy)&&styles.disabled]}><Text style={styles.newText}>＋</Text></Pressable></View>{error?<Text style={styles.error}>{error}</Text>:null}<FlatList data={items} keyExtractor={c=>c.id} renderItem={({item})=><Pressable style={styles.row} onPress={()=>open(item)}><View style={styles.avatar}><Text style={styles.avatarText}>{(item.otherUser?.nickname||item.otherUser?.username||"?")[0].toUpperCase()}</Text></View><View style={{flex:1}}><Text style={styles.name}>{item.otherUser?.nickname||"TwiTok user"}</Text><Text style={styles.preview} numberOfLines={1}>{item.lastMessagePreview||"Start a conversation"}</Text></View></Pressable>} ListEmptyComponent={<View style={styles.emptyWrap}><Text style={styles.empty}>No conversations yet.</Text></View>}/></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},header:{height:58,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:Colors.border},back:{color:Colors.text,fontSize:34},title:{color:Colors.text,...Typography.section},start:{flexDirection:"row",padding:14,gap:8},input:{flex:1,backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderRadius:10,color:Colors.text,...Typography.body,paddingHorizontal:13,paddingVertical:12},newButton:{width:48,borderRadius:10,backgroundColor:Colors.text,alignItems:"center",justifyContent:"center"},newText:{color:Colors.background,fontSize:24},disabled:{opacity:.45},row:{flexDirection:"row",alignItems:"center",padding:14,borderBottomWidth:1,borderBottomColor:Colors.border},avatar:{width:50,height:50,borderRadius:25,backgroundColor:Colors.surfaceRaised,alignItems:"center",justifyContent:"center",marginRight:12},avatarText:{color:Colors.text,...Typography.bodySemibold},name:{color:Colors.text,...Typography.bodySemibold},preview:{color:Colors.textSecondary,...Typography.caption,marginTop:3},error:{color:Colors.danger,...Typography.caption,textAlign:"center",paddingHorizontal:14},chat:{padding:14,paddingBottom:20},message:{alignSelf:"flex-end",maxWidth:"82%",backgroundColor:"#3131a8",borderRadius:16,padding:12,marginBottom:10},messageText:{color:Colors.text,...Typography.body},time:{color:"#bbb",fontSize:10,marginTop:4,textAlign:"right"},composer:{flexDirection:"row",padding:10,borderTopWidth:1,borderTopColor:Colors.border,gap:8},send:{width:48,borderRadius:10,backgroundColor:Colors.accent,alignItems:"center",justifyContent:"center"},sendText:{color:Colors.text,fontSize:22},emptyWrap:{padding:40,alignItems:"center"},empty:{color:Colors.textSecondary,...Typography.body,textAlign:"center"}});
