import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { getAuthToken } from "../lib/auth";
const API=process.env.EXPO_PUBLIC_TWITOK_API_URL??"http://localhost:4000/api/v1";
async function api(path:string,init:RequestInit={}){const token=await getAuthToken();if(!token)throw new Error("Please sign in first.");const r=await fetch(API+path,{...init,headers:{...(init.headers||{}),Authorization:`Bearer ${token}`,"Content-Type":"application/json"}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Seller request failed");return d}
const money=(n:number,c:string)=>`${c} ${(n/100).toFixed(2)}`;
export default function SellerCenter(){const [orders,setOrders]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[returns,setReturns]=useState<any[]>([]),[wallet,setWallet]=useState<any|null>(null),[payouts,setPayouts]=useState<any[]>([]),[carrier,setCarrier]=useState(""),[tracking,setTracking]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [o,i,r,w,p]=await Promise.all([api("/shop/seller/orders"),api("/shop/seller/inventory"),api("/shop/seller/returns"),api("/shop/seller/wallet"),api("/shop/seller/payouts")]);setOrders(o.orders||[]);setProducts(i.products||[]);setReturns(r.returnRequests||[]);setWallet(w);setPayouts(p.payouts||[])}catch(e){Alert.alert("Seller Center",e instanceof Error?e.message:"Unable to load")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const fulfill=async(id:string)=>{if(!carrier.trim()||!tracking.trim()){Alert.alert("Shipping","Enter carrier and tracking number.");return}try{await api("/shop/seller/orders/"+id+"/fulfill",{method:"POST",body:JSON.stringify({carrier,trackingNumber:tracking})});setCarrier("");setTracking("");await load()}catch(e){Alert.alert("Fulfillment",e instanceof Error?e.message:"Unable to ship")}};
 const deliver=async(id:string)=>{try{await api("/shop/seller/orders/"+id+"/deliver",{method:"POST"});await load()}catch(e){Alert.alert("Delivery",e instanceof Error?e.message:"Unable to mark delivered")}};
 const payout=async()=>{if(!wallet?.availableMinor||!wallet.currency)return;try{await api("/shop/seller/payouts",{method:"POST",body:JSON.stringify({amountMinor:wallet.availableMinor,currency:wallet.currency})});Alert.alert("Payout","Payout request submitted.");await load()}catch(e){Alert.alert("Payout",e instanceof Error?e.message:"Unable to request payout")}};
 const returnAction=async(id:string,action:"approve"|"reject"|"refund")=>{try{await api("/shop/seller/returns/"+id+"/"+action,{method:"POST"});await load()}catch(e){Alert.alert("Return",e instanceof Error?e.message:"Unable to update return")}};
 return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>Seller Center</Text></View>{loading?<View style={s.center}><ActivityIndicator color="#fff"/></View>:<ScrollView contentContainerStyle={s.pad}><View style={s.hero}><Text style={s.heroLabel}>Available balance</Text><Text style={s.balance}>{wallet?.availableMinor&&wallet?.currency?money(wallet.availableMinor,wallet.currency):"—"}</Text><Pressable style={s.payout} onPress={()=>void payout()}><Text style={s.payoutText}>Request payout</Text></Pressable><Text style={s.fine}>TwiTok Shop platform fee: 8%.</Text></View><Text style={s.section}>Orders</Text>{orders.length?orders.map(o=><View style={s.card} key={o.id}><Text style={s.name}>Order #{o.id.slice(0,8)} · {money(o.totalMinor,o.currency)}</Text><Text style={s.muted}>{o.status} · {o.paymentStatus}</Text>{o.status==="PAID"||o.status==="PROCESSING"?<><TextInput value={carrier} onChangeText={setCarrier} placeholder="Carrier" placeholderTextColor="#666" style={s.input}/><TextInput value={tracking} onChangeText={setTracking} placeholder="Tracking number" placeholderTextColor="#666" style={s.input}/><Pressable style={s.primary} onPress={()=>void fulfill(o.id)}><Text style={s.primaryText}>Mark shipped</Text></Pressable></>:null}{o.status==="SHIPPED"?<Pressable style={s.primary} onPress={()=>void deliver(o.id)}><Text style={s.primaryText}>Mark delivered</Text></Pressable>:null}</View>):<Text style={s.muted}>No paid seller orders yet.</Text>}<Text style={s.section}>Inventory</Text>{products.map(p=><View style={s.line} key={p.id}><Text style={s.name}>{p.name}</Text><Text style={s.muted}>Stock: {p.stock} · {p.status}</Text></View>)}<Text style={s.section}>Returns</Text>{returns.length?returns.map(r=><View style={s.card} key={r.id}><Text style={s.name}>Return #{r.id.slice(0,8)}</Text><Text style={s.muted}>{r.status} · {r.reason}</Text>{r.status==="REQUESTED"?<View style={s.actions}><Pressable onPress={()=>void returnAction(r.id,"approve")}><Text style={s.link}>Approve</Text></Pressable><Pressable onPress={()=>void returnAction(r.id,"reject")}><Text style={s.danger}>Reject</Text></Pressable></View>:null}{r.status==="APPROVED"?<Pressable style={s.primary} onPress={()=>void returnAction(r.id,"refund")}><Text style={s.primaryText}>Request refund</Text></Pressable>:null}</View>):<Text style={s.muted}>No return requests.</Text>}<Text style={s.section}>Payout history</Text>{payouts.map(p=><View style={s.line} key={p.id}><Text style={s.name}>{money(p.amountMinor,p.currency)}</Text><Text style={s.muted}>{p.status}</Text></View>)}</ScrollView>}</SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#000"},header:{height:58,flexDirection:"row",alignItems:"center",paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:"#222"},back:{color:"#fff",fontSize:34,width:40},title:{color:"#fff",fontSize:21,fontWeight:"900"},pad:{padding:14,paddingBottom:40},hero:{backgroundColor:"#171717",borderRadius:16,padding:18},heroLabel:{color:"#888"},balance:{color:"#fff",fontSize:32,fontWeight:"900",marginVertical:7},payout:{backgroundColor:"#ff2d55",padding:12,borderRadius:10,alignItems:"center"},payoutText:{color:"#fff",fontWeight:"900"},fine:{color:"#777",fontSize:11,marginTop:8},section:{color:"#fff",fontSize:19,fontWeight:"900",marginTop:24,marginBottom:10},card:{backgroundColor:"#121212",padding:14,borderRadius:12,marginBottom:10},line:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#222"},name:{color:"#fff",fontWeight:"800"},muted:{color:"#888",marginTop:4},input:{color:"#fff",backgroundColor:"#202020",borderRadius:9,padding:11,marginTop:8},primary:{backgroundColor:"#ff2d55",padding:12,borderRadius:9,alignItems:"center",marginTop:9},primaryText:{color:"#fff",fontWeight:"900"},actions:{flexDirection:"row",gap:24,marginTop:12},link:{color:"#61dafb",fontWeight:"800"},danger:{color:"#ff5b6e",fontWeight:"800"},center:{flex:1,alignItems:"center",justifyContent:"center"}});
