import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Image, Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { getAuthToken } from "../lib/auth";

const API = process.env.EXPO_PUBLIC_TWITOK_API_URL ?? "http://localhost:4000/api/v1";
type Product={id:string;name:string;description?:string;priceMinor:number;currency:string;images?:string[];stock:number;variants?:any[]};
type CartItem={productId:string;quantity:number;priceMinor:number;currency:string;name:string;image?:string|null};
const money=(n:number,c:string)=>`${c} ${(n/100).toFixed(2)}`;

async function api(path:string, init:RequestInit={}) {
  const token=await getAuthToken(); if(!token) throw new Error("Please sign in first.");
  const r=await fetch(API+path,{...init,headers:{...(init.headers||{}),Authorization:`Bearer ${token}`,"Content-Type":"application/json"}});
  const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.error||"Shop request failed"); return d;
}

export default function ShopScreen(){
 const { productId, tab: requestedTab } = useLocalSearchParams<{ productId?: string; tab?: string }>();
 const [products,setProducts]=useState<Product[]>([]),[q,setQ]=useState(""),[cart,setCart]=useState<CartItem[]>([]),[orders,setOrders]=useState<any[]>([]);
 const [tab,setTab]=useState<"shop"|"cart"|"orders">(requestedTab==="cart"?"cart":requestedTab==="orders"?"orders":"shop"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Product|null>(null),[shipments,setShipments]=useState<any[]>([]);
 const [shipName,setShipName]=useState(""),[shipPhone,setShipPhone]=useState(""),[shipAddress,setShipAddress]=useState("");
 const refresh=async()=>{setLoading(true);try{const [p,c,o]=await Promise.all([api("/shop/commerce/products"+(q.trim()?"?q="+encodeURIComponent(q.trim()):"")),api("/shop/cart"),api("/shop/orders")]);setProducts(p.products||[]);setCart(c.cart?.items||[]);setOrders(o.orders||[])}catch(e){Alert.alert("TwiTok Shop",e instanceof Error?e.message:"Unable to load Shop")}finally{setLoading(false)}};
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{ if(productId && products.length){ const found=products.find(p=>p.id===String(productId)); if(found)setSelected(found); } },[productId,products]);
 const subtotal=useMemo(()=>cart.reduce((s,i)=>s+i.priceMinor*i.quantity,0),[cart]);
 const add=async(p:Product)=>{try{setBusy(true);await api("/shop/cart/items",{method:"POST",body:JSON.stringify({productId:p.id,quantity:1})});setSelected(null);await refresh()}catch(e){Alert.alert("Cart",e instanceof Error?e.message:"Unable to add")}finally{setBusy(false)}};
 const checkout=async()=>{if(!cart.length)return;try{setBusy(true);const order=await api("/shop/checkout",{method:"POST",headers:{"Idempotency-Key":"shop_"+Date.now()+"_"+Math.random().toString(36).slice(2)},body:JSON.stringify({shippingAddress:{name:shipName.trim(),phone:shipPhone.trim(),address:shipAddress.trim()}})});const pay=await api("/shop/orders/"+order.order.id+"/pay",{method:"POST",body:JSON.stringify({channels:["card","mobile_money","bank","ussd"]})});if(pay.authorizationUrl)await Linking.openURL(pay.authorizationUrl);Alert.alert("Payment","Complete payment in the secure TwiTok payment page, then return to TwiTok.");await refresh()}catch(e){Alert.alert("Checkout",e instanceof Error?e.message:"Unable to checkout")}finally{setBusy(false)}};
 const loadShipments=async(id:string)=>{try{const d=await api("/shop/orders/"+id+"/shipments");setShipments(d.shipments||[])}catch(e){Alert.alert("Tracking",e instanceof Error?e.message:"Unable to load tracking")}};
 const requestReturn=async(id:string)=>{Alert.prompt("Request return","Tell the seller why you want to return this order.",async reason=>{if(!reason?.trim())return;try{await api("/shop/orders/"+id+"/return",{method:"POST",body:JSON.stringify({reason})});Alert.alert("Return requested","Your return request has been submitted.");await refresh()}catch(e){Alert.alert("Return",e instanceof Error?e.message:"Unable to request return")}},"plain-text","Reason")};
 return <SafeAreaView style={s.root}>
  <View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>TwiTok Shop</Text><Pressable onPress={()=>router.push("/seller-center")}><Text style={s.seller}>Seller</Text></Pressable></View>
  <View style={s.search}><TextInput value={q} onChangeText={setQ} onSubmitEditing={()=>void refresh()} placeholder="Search products" placeholderTextColor="#777" style={s.input}/><Pressable onPress={()=>void refresh()}><Text style={s.searchBtn}>Search</Text></Pressable></View>
  <View style={s.tabs}>{(["shop","cart","orders"] as const).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.tabOn]}><Text style={tab===x?s.tabTextOn:s.tabText}>{x==="shop"?"Discover":x==="cart"?`Cart (${cart.length})`:"Orders"}</Text></Pressable>)}</View>
  {loading?<View style={s.center}><ActivityIndicator color="#fff"/></View>:tab==="shop"?<FlatList data={products} numColumns={2} keyExtractor={x=>x.id} contentContainerStyle={s.grid} renderItem={({item})=><Pressable style={s.card} onPress={()=>setSelected(item)}><Image source={{uri:item.images?.[0]||"https://placehold.co/600x600/png"}} style={s.pic}/><Text style={s.name} numberOfLines={2}>{item.name}</Text><Text style={s.price}>{money(item.priceMinor,item.currency)}</Text><Text style={s.stock}>{item.stock>0?`${item.stock} available`:"Out of stock"}</Text></Pressable>}/>:tab==="cart"?<ScrollView contentContainerStyle={s.pad}>{cart.length===0?<Text style={s.empty}>Your cart is empty.</Text>:<>{cart.map(i=><View style={s.row} key={i.productId}><Image source={{uri:i.image||"https://placehold.co/120x120/png"}} style={s.thumb}/><View style={{flex:1}}><Text style={s.name}>{i.name}</Text><Text style={s.muted}>{i.quantity} × {money(i.priceMinor,i.currency)}</Text></View><Pressable onPress={async()=>{await api("/shop/cart/items/"+i.productId,{method:"DELETE"});await refresh()}}><Text style={s.remove}>Remove</Text></Pressable></View>)}<View style={s.total}><Text style={s.totalLabel}>Subtotal</Text><Text style={s.totalValue}>{money(subtotal,cart[0].currency)}</Text></View><TextInput value={shipName} onChangeText={setShipName} placeholder="Recipient name" placeholderTextColor="#666" style={s.checkoutInput}/><TextInput value={shipPhone} onChangeText={setShipPhone} keyboardType="phone-pad" placeholder="Phone number" placeholderTextColor="#666" style={s.checkoutInput}/><TextInput value={shipAddress} onChangeText={setShipAddress} placeholder="Delivery address" placeholderTextColor="#666" style={s.checkoutInput}/><Pressable disabled={busy||!shipName.trim()||!shipPhone.trim()||!shipAddress.trim()} style={s.primary} onPress={()=>void checkout()}><Text style={s.primaryText}>{busy?"Processing…":"Checkout"}</Text></Pressable><Text style={s.fine}>TwiTok Shop platform fee: 8% of completed sales. Payment methods: card, Mobile Money, bank transfer and USSD.</Text></>}</ScrollView>:<FlatList data={orders} keyExtractor={x=>x.id} contentContainerStyle={s.pad} renderItem={({item})=><View style={s.order}><View style={s.orderTop}><Text style={s.name}>Order #{String(item.id).slice(0,8)}</Text><Text style={s.status}>{item.status}</Text></View><Text style={s.muted}>{item.items?.length||0} item(s) · {money(item.totalMinor,item.currency)}</Text><Text style={s.muted}>{item.paymentStatus}</Text>{item.status==="DELIVERED"?<Pressable onPress={()=>requestReturn(item.id)}><Text style={s.link}>Request a return</Text></Pressable>:null}<Pressable onPress={()=>void loadShipments(item.id)}><Text style={s.link}>Track shipments</Text></Pressable></View>}/>}
  {shipments.length?<View style={s.modal}><ScrollView contentContainerStyle={s.modalCard}><Text style={s.heroTitle}>Seller shipments</Text>{shipments.map(x=><View style={s.order} key={x.sellerId}><Text style={s.name}>Seller {String(x.sellerId).slice(0,8)}</Text><Text style={s.muted}>{x.items?.length||0} item(s) · {x.status}</Text>{x.carrier?<Text style={s.muted}>{x.carrier} · {x.trackingNumber}</Text>:null}</View>)}<Pressable style={s.secondary} onPress={()=>setShipments([])}><Text style={s.secondaryText}>Close</Text></Pressable></ScrollView></View>:null}{selected?<View style={s.modal}><ScrollView contentContainerStyle={s.modalCard}>{selected.images?.[0]?<Image source={{uri:selected.images[0]}} style={s.hero}/>:null}<Text style={s.heroTitle}>{selected.name}</Text><Text style={s.heroPrice}>{money(selected.priceMinor,selected.currency)}</Text><Text style={s.description}>{selected.description||"Product details from the seller."}</Text><Text style={s.muted}>{selected.stock} in stock</Text><Pressable disabled={!selected.stock||busy} style={s.primary} onPress={()=>void add(selected)}><Text style={s.primaryText}>{busy?"Adding…":"Add to cart"}</Text></Pressable><Pressable style={s.secondary} onPress={()=>setSelected(null)}><Text style={s.secondaryText}>Close</Text></Pressable></ScrollView></View>:null}
 </SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#000"},header:{height:58,flexDirection:"row",alignItems:"center",paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:"#222"},back:{color:"#fff",fontSize:34,width:40},title:{color:"#fff",fontSize:21,fontWeight:"800",flex:1},seller:{color:"#ff2d55",fontWeight:"800"},search:{flexDirection:"row",margin:12,borderRadius:12,backgroundColor:"#171717",paddingLeft:12,alignItems:"center"},input:{flex:1,color:"#fff",height:44},searchBtn:{color:"#fff",fontWeight:"700",paddingHorizontal:14},tabs:{flexDirection:"row",borderBottomWidth:1,borderBottomColor:"#222"},tab:{flex:1,alignItems:"center",paddingVertical:12},tabOn:{borderBottomWidth:2,borderBottomColor:"#ff2d55"},tabText:{color:"#888"},tabTextOn:{color:"#fff",fontWeight:"800"},grid:{padding:8},card:{width:"50%",padding:7},pic:{width:"100%",aspectRatio:1,borderRadius:12,backgroundColor:"#161616"},name:{color:"#fff",fontSize:14,fontWeight:"700",marginTop:7},price:{color:"#fff",fontSize:16,fontWeight:"900",marginTop:3},stock:{color:"#888",fontSize:11,marginTop:3},center:{flex:1,alignItems:"center",justifyContent:"center"},pad:{padding:14},empty:{color:"#888",textAlign:"center",padding:50},row:{flexDirection:"row",alignItems:"center",paddingVertical:12,borderBottomWidth:1,borderBottomColor:"#222",gap:12},thumb:{width:64,height:64,borderRadius:8,backgroundColor:"#161616"},muted:{color:"#888",fontSize:13,marginTop:4},remove:{color:"#ff5b6e",fontSize:12},total:{flexDirection:"row",justifyContent:"space-between",paddingVertical:20},totalLabel:{color:"#aaa"},totalValue:{color:"#fff",fontSize:20,fontWeight:"900"},primary:{backgroundColor:"#ff2d55",padding:15,borderRadius:12,alignItems:"center",marginTop:8},primaryText:{color:"#fff",fontWeight:"900"},checkoutInput:{color:"#fff",backgroundColor:"#171717",borderRadius:10,padding:12,marginTop:8},secondary:{borderWidth:1,borderColor:"#444",padding:14,borderRadius:12,alignItems:"center",marginTop:10},secondaryText:{color:"#fff",fontWeight:"700"},fine:{color:"#777",fontSize:11,lineHeight:16,marginTop:12},order:{backgroundColor:"#121212",borderRadius:12,padding:14,marginBottom:10},orderTop:{flexDirection:"row",justifyContent:"space-between"},status:{color:"#ff2d55",fontWeight:"800"},link:{color:"#61dafb",fontWeight:"800",marginTop:10},modal:{position:"absolute",left:0,right:0,top:0,bottom:0,backgroundColor:"rgba(0,0,0,.82)",justifyContent:"flex-end"},modalCard:{backgroundColor:"#151515",borderTopLeftRadius:22,borderTopRightRadius:22,padding:18,minHeight:"60%"},hero:{width:"100%",aspectRatio:1,borderRadius:14,backgroundColor:"#222"},heroTitle:{color:"#fff",fontSize:24,fontWeight:"900",marginTop:12},heroPrice:{color:"#fff",fontSize:20,fontWeight:"900",marginTop:6},description:{color:"#ccc",fontSize:15,lineHeight:22,marginVertical:12}});