import { Router } from "express";
import { adminRouter } from "./admin.js";
import { moneyRouter } from "./money.js";
import { creatorRouter } from "./creator.js";
import { liveRouter } from "./live.js";
import { safetyRouter } from "./safety.js";
import { monetizationRouter } from "./monetization.js";
import { authRouter } from "./auth.js";
import { profileRouter } from "./profile.js";
import { videoRouter } from "./video.js";
import { feedRouter } from "./feed.js";
import { mediaRouter } from "./media.js";
import musicRouter from "./music.js";
import { messagesRouter } from "./messages.js";
import { engagementRouter } from "./engagement.js";
import { notificationsRouter } from "./notifications.js";
import { searchRouter } from "./search.js";
import { playlistsRouter } from "./playlists.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/profile", profileRouter);
apiRouter.use("/video", videoRouter);
apiRouter.use("/feed", feedRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/music", musicRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/money", moneyRouter);
apiRouter.use("/creator", creatorRouter);
apiRouter.use("/live", liveRouter);
apiRouter.use("/safety", safetyRouter);
apiRouter.use("/monetization", monetizationRouter);
apiRouter.use("/messages", messagesRouter);
apiRouter.use("/engagement", engagementRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/search", searchRouter);
apiRouter.use("/playlists", playlistsRouter);
