"use client";

import { FormEvent, useState, type CSSProperties } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

const API = process.env.NEXT_PUBLIC_TWITOK_API_URL ?? "http://localhost:4000/api/v1";

export default function RegisterPage() {
  const router=useRouter(); const [email,setEmail]=useState(""); const [phone,setPhone]=useState(""); const [password,setPassword]=useState(""); const [dob,setDob]=useState(""); const [countryCode,setCountryCode]=useState("GH"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();if(!email.trim()&&!phone.trim()){setError("Enter an email or phone number.");return}if(password.length<8){setError("Password must contain at least 8 characters.");return}setBusy(true);setError("");try{const r=await fetch(API+"/auth/register",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.trim()||undefined,phone:phone.trim()||undefined,password,dateOfBirth:dob,countryCode})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.token)throw new Error(d.error??"Unable to create account");localStorage.setItem("twitok_user_token",d.token);router.replace("/profile-setup")}catch(e){setError(e instanceof Error?e.message:"Unable to create account")}finally{setBusy(false)}}
  return <main style={styles.page}><form onSubmit={submit} style={styles.card}><Link href="/" style={styles.back}>← TwiTok</Link><h1>Create your account</h1><p style={styles.muted}>Join TwiTok. After signup, choose your unique username in Profile Setup.</p><input value={email} onChange={e=>setEmail(e.target.value)} style={styles.input} placeholder="Email address" type="email" autoCapitalize="none"/><div style={{display:"grid",gridTemplateColumns:"90px 1fr",gap:8}}><input value={countryCode} onChange={e=>setCountryCode(e.target.value.toUpperCase())} maxLength={3} style={styles.input} placeholder="GH"/><input value={phone} onChange={e=>setPhone(e.target.value)} style={styles.input} placeholder="Phone number"/></div><input value={password} onChange={e=>setPassword(e.target.value)} style={styles.input} placeholder="Password (minimum 8 characters)" type="password" minLength={8} required/><input value={dob} onChange={e=>setDob(e.target.value)} style={styles.input} placeholder="Date of birth (YYYY-MM-DD)" required/>{error?<p style={styles.error}>{error}</p>:null}<button disabled={busy} style={styles.primary}>{busy?"Creating account…":"Sign up"}</button><p style={styles.bottom}>Already have an account? <Link href="/login" style={styles.link}>Sign in</Link></p></form></main>;
}
const styles:Record<string,CSSProperties>={page:{minHeight:"100vh",background:"#000",color:"#fff",display:"grid",placeItems:"center",padding:24},card:{width:"100%",maxWidth:460,background:"#111",border:"1px solid #292929",borderRadius:24,padding:32},back:{color:"#25f4ee",textDecoration:"none"},muted:{color:"#999",lineHeight:1.6},input:{width:"100%",boxSizing:"border-box",marginTop:10,padding:"14px 15px",borderRadius:12,border:"1px solid #333",background:"#181818",color:"#fff"},primary:{width:"100%",marginTop:16,padding:15,border:0,borderRadius:12,background:"#fe2c55",color:"#fff",fontWeight:900,fontSize:16},error:{color:"#ff6b7f",fontSize:13},bottom:{textAlign:"center",color:"#999",marginTop:20},link:{color:"#25f4ee",fontWeight:900}};
