import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { getAuthToken } from "../lib/auth";
const API = process.env.EXPO_PUBLIC_TWITOK_API_URL ?? "http://localhost:4000/api/v1";
type Gift={giftId:string;name:string;coins:number;animation:string}; type Category="POPULAR"|"AFRICA"|"WORLD"|"PREMIUM";
type Props={visible:boolean;receiverId:string;videoId?:string;onClose:()=>void;onSent?:(gift:Gift,quantity:number)=>void};
const AFRICA:Record<string,string>={algeria:"DZ",angola:"AO",benin:"BJ",botswana:"BW",burkina_faso:"BF",burundi:"BI",cabo_verde:"CV",cameroon:"CM",central_african_republic:"CF",chad:"TD",comoros:"KM",congo:"CG",dr_congo:"CD",cote_divoire:"CI",djibouti:"DJ",egypt:"EG",equatorial_guinea:"GQ",eritrea:"ER",eswatini:"SZ",ethiopia:"ET",gabon:"GA",gambia:"GM",ghana:"GH",guinea:"GN",guinea_bissau:"GW",kenya:"KE",lesotho:"LS",liberia:"LR",libya:"LY",madagascar:"MG",malawi:"MW",mali:"ML",mauritania:"MR",mauritius:"MU",morocco:"MA",mozambique:"MZ",namibia:"NA",niger:"NE",nigeria:"NG",rwanda:"RW",sao_tome:"ST",senegal:"SN",seychelles:"SC",sierra_leone:"SL",somalia:"SO",south_africa:"ZA",south_sudan:"SS",sudan:"SD",tanzania:"TZ",togo:"TG",tunisia:"TN",uganda:"UG",zambia:"ZM",zimbabwe:"ZW"};
const WORLD:Record<string,string>={usa:"US",germany:"DE",canada:"CA",uk:"GB"};
function flag(code?:string){return !code||code.length!==2?"🎁":String.fromCodePoint(...code.toUpperCase().split("").map(c=>127397+c.charCodeAt(0)));}
function icon(g:Gift){if(g.giftId.endsWith("_flag")){const k=g.giftId.slice(0,-5);return flag(AFRICA[k]??WORLD[k]);}const m:Record<string,string>={rose:"🌹",heart:"❤️",clap:"👏",kente:"🧵",gold_drum:"🥁",royal_crown:"👑",golden_lion:"🦁",diamond_kingdom:"💎",twitok_cap:"🧢",money_gun:"💵",wedding_rings:"💍",flying_angels:"👼"};return m[g.giftId]??"🎁";}
export default function GiftTray({visible,receiverId,videoId,onClose,onSent}:Props){
 const [gifts,setGifts]=useState<Gift[]>([]); const [coins,setCoins]=useState(0); const [category,setCategory]=useState<Category>("POPULAR"); const [selected,setSelected]=useState<Gift|null>(null); const [quantity,setQuantity]=useState(1); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const token=await getAuthToken();const headers:Record<string,string>={};if(token)headers.Authorization="Bearer "+token;const [a,b]=await Promise.all([fetch(API+"/wallet/catalog",{headers}),fetch(API+"/wallet/me",{headers})]);const ad=await a.json().catch(()=>({}));const bd=await b.json().catch(()=>({}));if(!a.ok)throw new Error(ad.error??"Gift catalog unavailable");setGifts(ad.gifts??[]);setCoins(Number(bd.coinBalance??0));}catch(e){setError(e instanceof Error?e.message:"Unable to load gifts");}finally{setLoading(false);}}
 useEffect(()=>{if(visible)void load();},[visible]);
 const shown=useMemo(()=>{const flags=gifts.filter(g=>g.giftId.endsWith("_flag"));if(category==="AFRICA")return flags.filter(g=>!["usa_flag","germany_flag","canada_flag","uk_flag"].includes(g.giftId));if(category==="WORLD")return flags.filter(g=>["usa_flag","germany_flag","canada_flag","uk_flag"].includes(g.giftId));if(category==="PREMIUM")return gifts.filter(g=>!g.giftId.endsWith("_flag")&&g.coins>=500);return gifts.filter(g=>!g.giftId.endsWith("_flag")&&g.coins<500);},[category,gifts]);
 const total=(selected?.coins??0)*quantity; const insufficient=!!selected&&coins<total;
 async function send(){if(!selected||insufficient||busy)return;setBusy(true);setError("");try{const token=await getAuthToken();if(!token)throw new Error("Sign in to send gifts");const r=await fetch(API+"/wallet/gifts",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token,"Idempotency-Key":String(Date.now())+"-"+Math.random().toString(36).slice(2)},body:JSON.stringify({receiverId,giftId:selected.giftId,quantity,context:"VIDEO",videoId})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Gift failed");setCoins(c=>Math.max(0,c-Number(d.coinsSpent??total)));onSent?.(selected,quantity);setSelected(null);setQuantity(1);}catch(e){setError(e instanceof Error?e.message:"Gift failed");}finally{setBusy(false);}}
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><View style={s.sheet}><View style={s.header}><View><Text style={s.title}>Send a Gift</Text><Text style={s.balance}>🪙 {coins.toLocaleString()} Coins</Text></View><Pressable onPress={onClose}><Text style={s.close}>×</Text></Pressable></View>
 <View style={s.categories}>{(["POPULAR","AFRICA","WORLD","PREMIUM"] as Category[]).map(c=><Pressable key={c} onPress={()=>{setCategory(c);setSelected(null)}} style={[s.category,category===c&&s.categoryActive]}><Text style={[s.categoryText,category===c&&s.categoryTextActive]}>{c==="AFRICA"?"🌍 Africa":c==="WORLD"?"🌐 World":c==="PREMIUM"?"✨ Premium":"🔥 Popular"}</Text></Pressable>)}</View>
 {loading?<View style={s.loading}><ActivityIndicator color="#fff"/><Text style={s.muted}>Loading gifts…</Text></View>:<ScrollView contentContainerStyle={s.grid}>{shown.map(g=><Pressable key={g.giftId} onPress={()=>setSelected(g)} style={[s.gift,selected?.giftId===g.giftId&&s.giftSelected]}><Text style={s.icon}>{icon(g)}</Text><Text style={s.name} numberOfLines={1}>{g.name.replace(" Flag","")}</Text><Text style={s.price}>🪙 {g.coins}</Text></Pressable>)}{!shown.length&&<Text style={s.muted}>No gifts in this category yet.</Text>}</ScrollView>}
 {selected&&<View style={s.footer}><View style={s.selectedRow}><Text style={s.selectedText}>{icon(selected)} {selected.name}</Text><View style={s.qty}><Pressable onPress={()=>setQuantity(q=>Math.max(1,q-1))}><Text style={s.qtyButton}>−</Text></Pressable><Text style={s.qtyValue}>×{quantity}</Text><Pressable onPress={()=>setQuantity(q=>Math.min(100,q+1))}><Text style={s.qtyButton}>+</Text></Pressable></View></View><View style={s.quickQty}>{[1,5,10,25,100].map(q=><Pressable key={q} onPress={()=>setQuantity(q)} style={[s.quick,quantity===q&&s.quickActive]}><Text style={s.quickText}>×{q}</Text></Pressable>)}</View>{insufficient?<View style={s.insufficient}><Text style={s.insufficientText}>You have {coins.toLocaleString()} Coins, but need {total.toLocaleString()}.</Text><Pressable onPress={()=>{onClose();router.push("/wallet")}}><Text style={s.buyCoins}>Buy Coins →</Text></Pressable></View>:<Pressable disabled={busy} onPress={()=>void send()} style={s.send}><Text style={s.sendText}>{busy?"Sending…":"Send Gift · 🪙 "+total.toLocaleString()}</Text></Pressable>}{!!error&&<Text style={s.error}>{error}</Text>}</View>}</View></View></Modal>;
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.68)",justifyContent:"flex-end"},sheet:{height:"72%",backgroundColor:"#111",borderTopLeftRadius:22,borderTopRightRadius:22,borderWidth:1,borderColor:"#292929",paddingTop:14},header:{paddingHorizontal:16,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{color:"#fff",fontSize:20,fontWeight:"900"},balance:{color:"#aaa",fontSize:12,marginTop:3},close:{color:"#fff",fontSize:32,lineHeight:32},categories:{flexDirection:"row",paddingHorizontal:10,marginTop:12,borderBottomWidth:1,borderBottomColor:"#292929"},category:{paddingHorizontal:9,paddingVertical:11},categoryActive:{borderBottomWidth:2,borderBottomColor:"#ff2d55"},categoryText:{color:"#888",fontSize:11,fontWeight:"800"},categoryTextActive:{color:"#fff"},grid:{padding:12,flexDirection:"row",flexWrap:"wrap",gap:8,paddingBottom:130},gift:{width:"23.5%",minHeight:94,borderRadius:12,backgroundColor:"#191919",borderWidth:1,borderColor:"#292929",alignItems:"center",justifyContent:"center",padding:6},giftSelected:{borderColor:"#ff2d55",backgroundColor:"#24151a"},icon:{fontSize:30,height:38,textAlign:"center"},name:{color:"#ddd",fontSize:10,fontWeight:"800",textAlign:"center"},price:{color:"#888",fontSize:9,marginTop:4},loading:{flex:1,alignItems:"center",justifyContent:"center",gap:8},muted:{color:"#888",padding:16,textAlign:"center"},footer:{position:"absolute",bottom:0,left:0,right:0,backgroundColor:"#151515",borderTopWidth:1,borderTopColor:"#292929",padding:12,paddingBottom:24},selectedRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},selectedText:{color:"#fff",fontWeight:"900",flex:1},qty:{flexDirection:"row",alignItems:"center",gap:14},qtyButton:{color:"#fff",fontSize:23,fontWeight:"900"},qtyValue:{color:"#fff",fontWeight:"900"},quickQty:{flexDirection:"row",gap:7,marginTop:9},quick:{paddingHorizontal:10,paddingVertical:6,borderRadius:8,backgroundColor:"#222"},quickActive:{backgroundColor:"#ff2d55"},quickText:{color:"#fff",fontSize:11,fontWeight:"800"},send:{backgroundColor:"#ff2d55",borderRadius:11,padding:13,alignItems:"center",marginTop:10},sendText:{color:"#fff",fontWeight:"900"},insufficient:{backgroundColor:"#21171a",borderRadius:11,padding:10,marginTop:10,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},insufficientText:{color:"#ffb8c4",fontSize:11,flex:1},buyCoins:{color:"#fff",fontWeight:"900"},error:{color:"#ff7188",fontSize:11,textAlign:"center",marginTop:8},loadingText:{color:"#fff"}});